services:
  service-registry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        SECURITY_USER_NAME: ${SECURITY_USER_NAME}
        SECURITY_USER_PASSWORD: ${SECURITY_USER_PASSWORD}

    container_name: service-registry

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    restart: unless-stopped