spring.application.name=service-registry
server.port=${PORT}

eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.client.healthcheck.enabled=true
spring.cloud.refresh.enabled=false

spring.security.user.name=${SECURITY_USER_NAME}
spring.security.user.password=${SECURITY_USER_PASSWORD}